version: "3.8"

services:
  app:
    image: laravel-task
    ports:
      - 80:8000
      - 22:22
    volumes:
      - .\laravel_task:/var/www/html/task
    networks:
      - laravel
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lead
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .\.data\mysql:/var/lib/mysql
      - .\.data\docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - laravel

networks:
  laravel:
    driver: bridge